#!/bin/dash

# grim -g "$(swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | swappy -f -
# notify-send -t 3000 "Focused Window Screenshot" "A screenshot of your focused window has been opened and edited in swappy."
notify-send -t 7000 " " "You are not running sway.\n"
