#!/bin/dash

pr=$(echo "Poweroff\nReboot" | fuzzel -d) > /dev/null 2>&1

case "$pr" in
    Poweroff)
        ck="$(echo "$(~/.config/dwlmsh/check-dwltags-dm2)" | grep check)"
        if [ -z "$ck" ]; then
            systemctl poweroff
        else
            notify-send -t 9000 " " "$ck\n_"
        fi
        ;;
    Reboot)
        ck="$(echo "$(~/.config/dwlmsh/check-dwltags-dm2)" | grep check)"
        if [ -z "$ck" ]; then
            systemctl reboot
        else
            notify-send -t 9000 " " "$ck\n_"
        fi
        ;;
    *)
        notify-send -t 7000 " " "Fuck You, Man!\n_"
        exit
esac
