#!/bin/dash
ck=$(cat /sys/class/drm/card0-HDMI-A-1/modes)
if [ ! -z "$ck" ]; then
    resxy=$(cat /sys/class/drm/card0-HDMI-A-1/modes | bemenu)
    ckresxy=$(cat /sys/class/drm/card0-HDMI-A-1/modes | grep "$resxy")
    if [ ! -z "$resxy" ] && [ ! -z "$ckresxy" ]; then
        resx=$(echo "$resxy" | cut -d'x' -f1)
        resxx=$((resx+5))
        resy=$(echo "$resxy" | cut -d'x' -f2)
        resyy=$((resx+5))
        side=$(echo "LEFT\nRIGHT" | bemenu)
        case "$side" in
            LEFT)
                wlr-randr --output HDMI-A-1 --pos 0,$resyy --mode $resxy
                wlr-randr --output eDP-1 --pos $resxx,0 --mode 1920x1080
                wlr-randr --output HDMI-A-1 --pos 0,0 --mode $resxy
                notify-send -t 5000 "Configuring External Monitor/Screen" "HDMI-A-1 has been configured\non the $side of eDP-1."
                ;;
            RIGHT)
                wlr-randr --output HDMI-A-1 --pos 0,$resyy --mode $resxy
                wlr-randr --output eDP-1 --pos 0,0 --mode 1920x1080
                wlr-randr --output HDMI-A-1 --pos 1925,0 --mode $resxy
                notify-send -t 5000 "Configuring External Monitor/Screen" "HDMI-A-1 has been configured\non the $side of eDP-1."
                ;;
            *)
                exit 0
                ;;
        esac
    else
        notify-send -t 900 " " "clean exit\n_"
        exit 0
    fi
else
    notify-send -t 900 " " "No External Monitor/Screen\nHDMI-A-1 is not pluged in.\n_"
fi > /dev/null 2>&1
