#!/bin/dash

passfiles=$(find ~/.password-store -name "*.gpg" | sed 's/\/home\/msh\/\.password-store\///;s/\.gpg//')

selpassfile=$(echo "$passfiles" | bemenu)
ckspassfile=$(echo "$passfiles" | grep "$selpassfile")
if [ ! -z "$selpassfile" ] && [ ! -z "$ckspassfile" ]; then
    pass show "$selpassfile" | wl-copy
    notify-send -t 900 " " "Your password has been copied to clipboard\n_"
else
    notify-send -t 900 " " "clean exit\n_"
fi
