#!/bin/dash

pr=$(echo "Poweroff\nReboot" | bemenu)

case "$pr" in
    Poweroff)
        systemctl poweroff
        ;;
    Reboot)
        systemctl reboot
        ;;
    *)
        notify-send -t 7000 " " "Fuck You, Man!\n_"
        exit
esac
