#!/bin/dash

fdir="$(dirname "$(readlink -f "$0")")"

cd "$fdir"/sssc
sel=$(ls . | wofi -k /dev/null -d)
if [ -f "$sel" ] && [ -x "$sel" ]; then
    ./"$sel"
else
    notify-send -t 900 " " "clean exit\n_"
fi
