#!/bin/dash

passfiles=$(find ~/.password-store -name "*.gpg" | sed 's/\/home\/msh\/\.password-store\///;s/\.gpg//')

# selpassfile=$(echo "$passfiles" | bemenu --fn "monospace 20" -l 12 -p "passwords: ")
# selpassfile=$(echo "$passfiles" | fuzzel -d)

selpassfile=$(echo "$passfiles" | wofi -d -p "Passwords: ")
ckspassfile=$(echo "$passfiles" | grep "$selpassfile")
# [ ! -z "$selpassfile" ] && pass show "$selpassfile" | wl-copy
if [ ! -z "$selpassfile" ] && [ ! -z "$ckspassfile" ]; then
    pass show "$selpassfile" | wl-copy
    notify-send -t 900 " " "Your password has been copied to clipboard\n_"
else
    notify-send -t 900 " " "clean exit\n_"
fi
