#!/bin/dash

fdir="$(dirname "$(readlink -f "$0")")"
bdir="$(dirname "$fdir")"

cd "$bdir"/mnlogs/dolistsc

sel=$(ls . | fuzzel -d) > /dev/null
if [ -f "$sel" ] && [ -x "$sel" ]; then
    ./"$sel" &
else
    notify-send -t 900 " " "clean exit\n_"
fi
