#!/bin/dash

fdir="$(dirname "$(readlink -f "$0")")"

case $1 in
    update)
        alacritty -t "mshcfloat" -e nvim "$fdir"/directopenlist & > /dev/null 2>&1
        ;;
    gen)
        "$fdir"/dolistgen &
        ;;
    *)
        exit 0
        ;;
esac
